services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: tirunmarketing/marketplace:latest
    container_name: marketplace
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000